### ISSUE TITLE
How to force commitlint to run with "pre-commit run -a"

### ISSUE THREAD

**Issue by ssbarnea** [alessandrojcm/commitlint-pre-commit-hook#53]
While it is very useful to run commitlint during `commit-msg` phase, I do not like the fact that it is skipped from the normal run of `pre-commit run --all`.

I tried to hack it to include the `commit` stage but while it was called, it failed ugly trying to parse received input from pre-commit.

Is there a way to run commitlint in manual execution of pre-commit? that is very useful for several use cases: people that do not want to install hooks, those that do not know how to install them and also CI usage.

While the CI/CD use-case can be worked-around by adding a extra command, it would be awesome to be able to use a single command for running all pre-commit checks.

**Comment by alessandrojcm** [comment]
Hi @ssbarnea, sorry for taking too long to respond to this. AFAIK, the `commit-msg` stage does not get executed when calling `pre-commit run --all` because that stage does not retroactively work on your commit history (unlike other kinds of hooks that work directly on your source code, like linters or formatters); it works only on the commit stage because that is when the commit message is available. So I'm not sure we would be able to accomplish this.

One way I _think_ you could do this is by getting the commit messages between two hashes (something like [this](https://stackoverflow.com/questions/6703238/getting-a-list-of-commits-along-with-the-commit-message-and-hash-in-git)), writing them into a file, and then [executing the hook over that file](https://pre-commit.com/#developing-hooks-interactively). But this kinda defeats the purpose of the hook IMO, precisely the idea of this hook is to prevent malformed commit messages from reaching the remote repo.

**Comment by alessandrojcm** [comment]
I will close this since is kinda out of scope; let me know if you need any more help.

**Comment by ssbarnea** [comment]
I can understand that this is not really fixable from here. I will mention the upstream feature request in case someone is looking for it: https://github.com/pre-commit-ci/issues/issues/35
